/* eslint-disable camelcase */
import type { Metadata } from "next";
import { Saira_Condensed } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "@/components/shared/navbar/Navbar";

const sairaCondesed = Saira_Condensed({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-sairaCondensed",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${sairaCondesed.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
